# version: '3.4'

# services:
#   revent.auth:
#     image: ${DOCKER_REGISTRY-}reventauth
#     build:
#       context: .
#       dockerfile: Revent.Auth/Dockerfile

#   revent.webapi:
#     image: ${DOCKER_REGISTRY-}reventwebapi
#     build:
#       context: .
#       dockerfile: Revent.WebApi/Dockerfile


# in build we specify docker file 
# when we run docker compose under the hood a network is created with each host for each service and name of host is same as service name
services: # all the container are specified under services
  revent.auth:
    image: ${DOCKER_REGISTRY-}reventauth
    build:
      context: .
      dockerfile: Revent.Auth/Dockerfile

  revent.webapi:
    image: ${DOCKER_REGISTRY-}reventwebapi
    build:
      context: .
      dockerfile: Revent.WebApi/Dockerfile
  revent.emailconsumer:
    image: ${DOCKER_REGISTRY-}reventemailconsumer
    build:
        context: .
        dockerfile: Revent.EmailConsumer/Dockerfile

  postgres:
    image: postgres:16.3
    container_name: my_postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=reventDb
    volumes:
      - ./DatabaseFolder/pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - default
  redis:
    image: redis:latest   # Use the official Redis image
    container_name: redis_cache
    ports:
      - "6379:6379"       # Redis default port
    networks:
      - default
  rabbitMQ:
    image: rabbitmq:management
    container_name: rabbitMQ_container
    environment:
      - hostname=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - default

networks:
  default:
    driver: bridge


