// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Revent.DataAccess.Implementation.DbContexts;

#nullable disable

namespace Revent.DataAccess.Implementation.Migrations.ReventDb
{
    [DbContext(typeof(ReventDbContext))]
    partial class ReventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Revent.EFCore.DataModel.Models.Temp", b =>
                {
                    b.Property<string>("Column1")
                        .HasColumnType("character varying")
                        .HasColumnName("column1");

                    b.ToTable("Temp");
                });
#pragma warning restore 612, 618
        }
    }
}
